package com.example.learnenglish.activity;
import android.content.Intent;
import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Environment;
import android.support.annotation.NonNull;
import android.support.design.widget.NavigationView;
import android.support.v4.view.GravityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.MenuItem;
import android.view.View;
import android.widget.Toast;

import com.example.learnenglish.R;


import java.io.File;
import java.io.FileOutputStream;
import java.util.Date;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import java.util.HashMap;
import java.util.Map;

import java.util.HashMap;
import java.util.Map;

public class ChatActivity extends AppCompatActivity {

    private EditText messageInput;
    private Button sendButton;
    private LinearLayout chatContainer;
    private ScrollView scrollView;

    private Map<String, DictionaryEntry> dictionary;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_chat); // Đảm bảo tên layout chính xác

        messageInput = findViewById(R.id.messageInput);
        sendButton = findViewById(R.id.sendButton);
        chatContainer = findViewById(R.id.chatContainer);
        scrollView = findViewById(R.id.scrollView);

        // Initialize the dictionary with hard-coded values
        dictionary = new HashMap<>();
        dictionary.put("dolphin", new DictionaryEntry("(n):", "cá heo", "Dolphin is an intelligent animal."));
        dictionary.put("dolphin", new DictionaryEntry("(n):", "cá heo", "Dolphin is an intelligent animal."));
        dictionary.put("apple", new DictionaryEntry("(n):", "quả táo", "She ate a juicy apple."));
        dictionary.put("book", new DictionaryEntry("(n):", "sách", "I am reading a book."));
        dictionary.put("run", new DictionaryEntry("(v):", "chạy", "He likes to run in the park."));
        dictionary.put("happy", new DictionaryEntry("(adj):", "hạnh phúc", "She felt very happy today."));
        dictionary.put("house", new DictionaryEntry("(n):", "nhà", "They live in a big house."));
        dictionary.put("computer", new DictionaryEntry("(n):", "máy tính", "She uses her computer to work."));
        dictionary.put("write", new DictionaryEntry("(v):", "viết", "He will write a letter to his friend."));
        dictionary.put("beautiful", new DictionaryEntry("(adj):", "đẹp", "The sunset was beautiful."));
        dictionary.put("dog", new DictionaryEntry("(n):", "chó", "The dog barked loudly."));
        dictionary.put("car", new DictionaryEntry("(n):", "ô tô", "They bought a new car."));
        dictionary.put("quick", new DictionaryEntry("(adj):", "nhanh", "She is a quick learner."));
        dictionary.put("sky", new DictionaryEntry("(n):", "bầu trời", "The sky was clear and blue."));
        dictionary.put("food", new DictionaryEntry("(n):", "thức ăn", "I love Italian food."));
        dictionary.put("train", new DictionaryEntry("(n):", "tàu hỏa", "The train departed on time."));
        dictionary.put("city", new DictionaryEntry("(n):", "thành phố", "New York is a busy city."));
        dictionary.put("river", new DictionaryEntry("(n):", "con sông", "The river flows through the valley."));
        dictionary.put("mountain", new DictionaryEntry("(n):", "núi", "They climbed the highest mountain."));
        dictionary.put("light", new DictionaryEntry("(n):", "ánh sáng", "The room was filled with light."));
        dictionary.put("flower", new DictionaryEntry("(n):", "hoa", "She picked a beautiful flower."));
        dictionary.put("chair", new DictionaryEntry("(n):", "ghế", "He sat in the comfortable chair."));
        dictionary.put("music", new DictionaryEntry("(n):", "âm nhạc", "I enjoy listening to classical music."));
        dictionary.put("tea", new DictionaryEntry("(n):", "trà", "She drank a cup of green tea."));
        dictionary.put("phone", new DictionaryEntry("(n):", "điện thoại", "My phone is out of battery."));
        dictionary.put("movie", new DictionaryEntry("(n):", "phim", "They watched a thrilling movie."));
        dictionary.put("pen", new DictionaryEntry("(n):", "bút", "He wrote with a blue pen."));
        dictionary.put("shirt", new DictionaryEntry("(n):", "áo sơ mi", "He wore a white shirt."));
        dictionary.put("window", new DictionaryEntry("(n):", "cửa sổ", "The window was open to let in fresh air."));
        dictionary.put("key", new DictionaryEntry("(n):", "chìa khóa", "She lost her house key."));
        dictionary.put("river", new DictionaryEntry("(n):", "con sông", "The river was flowing gently."));
        dictionary.put("street", new DictionaryEntry("(n):", "đường phố", "They walked down the busy street."));
        dictionary.put("hotel", new DictionaryEntry("(n):", "khách sạn", "They stayed at a luxurious hotel."));
        dictionary.put("dog", new DictionaryEntry("(n):", "chó", "The dog wagged its tail."));
        dictionary.put("park", new DictionaryEntry("(n):", "công viên", "They had a picnic in the park."));
        dictionary.put("desk", new DictionaryEntry("(n):", "bàn làm việc", "The desk was cluttered with papers."));
        dictionary.put("fish", new DictionaryEntry("(n):", "cá", "The fish swam in the aquarium."));
        dictionary.put("clock", new DictionaryEntry("(n):", "đồng hồ", "The clock struck midnight."));
        dictionary.put("sun", new DictionaryEntry("(n):", "mặt trời", "The sun was shining brightly."));
        dictionary.put("dolphin", new DictionaryEntry("(n):", "cá heo", "Dolphin is an intelligent animal."));
        dictionary.put("apple", new DictionaryEntry("(n):", "quả táo", "She ate a juicy apple."));
        dictionary.put("book", new DictionaryEntry("(n):", "sách", "I am reading a book."));
        dictionary.put("run", new DictionaryEntry("(v):", "chạy", "He likes to run in the park."));
        dictionary.put("happy", new DictionaryEntry("(adj):", "hạnh phúc", "She felt very happy today."));
        dictionary.put("house", new DictionaryEntry("(n):", "nhà", "They live in a big house."));
        dictionary.put("computer", new DictionaryEntry("(n):", "máy tính", "She uses her computer to work."));
        dictionary.put("write", new DictionaryEntry("(v):", "viết", "He will write a letter to his friend."));
        dictionary.put("beautiful", new DictionaryEntry("(adj):", "đẹp", "The sunset was beautiful."));
        dictionary.put("dog", new DictionaryEntry("(n):", "chó", "The dog barked loudly."));
        dictionary.put("car", new DictionaryEntry("(n):", "ô tô", "They bought a new car."));
        dictionary.put("quick", new DictionaryEntry("(adj):", "nhanh", "She is a quick learner."));
        dictionary.put("sky", new DictionaryEntry("(n):", "bầu trời", "The sky was clear and blue."));
        dictionary.put("food", new DictionaryEntry("(n):", "thức ăn", "I love Italian food."));
        dictionary.put("train", new DictionaryEntry("(n):", "tàu hỏa", "The train departed on time."));
        dictionary.put("city", new DictionaryEntry("(n):", "thành phố", "New York is a busy city."));
        dictionary.put("river", new DictionaryEntry("(n):", "con sông", "The river flows through the valley."));
        dictionary.put("mountain", new DictionaryEntry("(n):", "núi", "They climbed the highest mountain."));
        dictionary.put("light", new DictionaryEntry("(n):", "ánh sáng", "The room was filled with light."));
        dictionary.put("flower", new DictionaryEntry("(n):", "hoa", "She picked a beautiful flower."));
        dictionary.put("chair", new DictionaryEntry("(n):", "ghế", "He sat in the comfortable chair."));
        dictionary.put("music", new DictionaryEntry("(n):", "âm nhạc", "I enjoy listening to classical music."));
        dictionary.put("tea", new DictionaryEntry("(n):", "trà", "She drank a cup of green tea."));
        dictionary.put("phone", new DictionaryEntry("(n):", "điện thoại", "My phone is out of battery."));
        dictionary.put("movie", new DictionaryEntry("(n):", "phim", "They watched a thrilling movie."));
        dictionary.put("pen", new DictionaryEntry("(n):", "bút", "He wrote with a blue pen."));
        dictionary.put("shirt", new DictionaryEntry("(n):", "áo sơ mi", "He wore a white shirt."));
        dictionary.put("window", new DictionaryEntry("(n):", "cửa sổ", "The window was open to let in fresh air."));
        dictionary.put("key", new DictionaryEntry("(n):", "chìa khóa", "I can't find my house key."));
        dictionary.put("table", new DictionaryEntry("(n):", "bàn", "The book is on the table."));
        dictionary.put("ball", new DictionaryEntry("(n):", "quả bóng", "He kicked the ball across the field."));
        dictionary.put("tree", new DictionaryEntry("(n):", "cây", "The tree is full of green leaves."));
        dictionary.put("water", new DictionaryEntry("(n):", "nước", "She drank a glass of water."));
        dictionary.put("school", new DictionaryEntry("(n):", "trường học", "They go to school every day."));
        dictionary.put("computer", new DictionaryEntry("(n):", "máy tính", "His computer is very fast."));
        dictionary.put("house", new DictionaryEntry("(n):", "nhà", "They live in a large house."));
        dictionary.put("train", new DictionaryEntry("(n):", "tàu hỏa", "The train arrives at noon."));
        dictionary.put("airport", new DictionaryEntry("(n):", "sân bay", "We arrived at the airport early."));
        dictionary.put("book", new DictionaryEntry("(n):", "sách", "She borrowed a book from the library."));
        dictionary.put("restaurant", new DictionaryEntry("(n):", "nhà hàng", "They had dinner at a fancy restaurant."));
        dictionary.put("television", new DictionaryEntry("(n):", "tivi", "They watched a movie on the television."));
        dictionary.put("car", new DictionaryEntry("(n):", "ô tô", "His car is parked outside."));
        dictionary.put("mountain", new DictionaryEntry("(n):", "núi", "They hiked up the mountain."));
        dictionary.put("lake", new DictionaryEntry("(n):", "hồ", "The lake was calm and serene."));
        dictionary.put("park", new DictionaryEntry("(n):", "công viên", "The children played in the park."));
        dictionary.put("dog", new DictionaryEntry("(n):", "chó", "The dog followed him everywhere."));
        dictionary.put("fish", new DictionaryEntry("(n):", "cá", "The fish swam in the pond."));
        dictionary.put("bus", new DictionaryEntry("(n):", "xe buýt", "She takes the bus to work."));
        dictionary.put("computer", new DictionaryEntry("(n):", "máy tính", "He uses his computer for work."));
        dictionary.put("phone", new DictionaryEntry("(n):", "điện thoại", "She answered her phone quickly."));
        dictionary.put("train", new DictionaryEntry("(n):", "tàu hỏa", "The train is late today."));
        dictionary.put("river", new DictionaryEntry("(n):", "con sông", "They walked along the river."));
        dictionary.put("book", new DictionaryEntry("(n):", "sách", "The book is on the shelf."));
        dictionary.put("car", new DictionaryEntry("(n):", "ô tô", "His car broke down."));
        dictionary.put("tree", new DictionaryEntry("(n):", "cây", "The tree is very old."));
        dictionary.put("apple", new DictionaryEntry("(n):", "quả táo", "She ate a red apple."));
        dictionary.put("chair", new DictionaryEntry("(n):", "ghế", "The chair is comfortable."));
        dictionary.put("phone", new DictionaryEntry("(n):", "điện thoại", "He lost his phone."));
        dictionary.put("computer", new DictionaryEntry("(n):", "máy tính", "The computer needs repair."));
        dictionary.put("shirt", new DictionaryEntry("(n):", "áo sơ mi", "He bought a new shirt."));
        dictionary.put("car", new DictionaryEntry("(n):", "ô tô", "The car is very fast."));
        dictionary.put("pencil", new DictionaryEntry("(n):", "bút chì", "She used a pencil to draw."));
        dictionary.put("bread", new DictionaryEntry("(n):", "bánh mì", "They ate fresh bread."));
        dictionary.put("desk", new DictionaryEntry("(n):", "bàn làm việc", "He worked at his desk."));
        dictionary.put("window", new DictionaryEntry("(n):", "cửa sổ", "She looked out the window."));
        dictionary.put("cat", new DictionaryEntry("(n):", "mèo", "The cat slept on the couch."));
        dictionary.put("clock", new DictionaryEntry("(n):", "đồng hồ", "The clock struck twelve."));
        dictionary.put("laptop", new DictionaryEntry("(n):", "máy tính xách tay", "He uses a laptop for school."));
        dictionary.put("map", new DictionaryEntry("(n):", "bản đồ", "The map showed the way."));
        dictionary.put("helmet", new DictionaryEntry("(n):", "mũ bảo hiểm", "He wore a helmet for safety."));
        dictionary.put("key", new DictionaryEntry("(n):", "chìa khóa", "She lost her car key."));
        dictionary.put("camera", new DictionaryEntry("(n):", "máy ảnh", "He took a photo with his camera."));
        dictionary.put("door", new DictionaryEntry("(n):", "cửa", "The door was open."));
        dictionary.put("milk", new DictionaryEntry("(n):", "sữa", "She poured milk into a glass."));

        dictionary.put("cup", new DictionaryEntry("(n):", "cốc", "He drank coffee from a cup."));
        dictionary.put("boat", new DictionaryEntry("(n):", "thuyền", "They sailed across the lake in a boat."));
        dictionary.put("bag", new DictionaryEntry("(n):", "túi", "She carried a heavy bag."));
        dictionary.put("spoon", new DictionaryEntry("(n):", "thìa", "He ate soup with a spoon."));
        dictionary.put("glove", new DictionaryEntry("(n):", "găng tay", "She wore gloves in the winter."));
        dictionary.put("carpet", new DictionaryEntry("(n):", "thảm", "The carpet was soft and warm."));
        dictionary.put("magazine", new DictionaryEntry("(n):", "tạp chí", "She read a magazine in the waiting room."));
        dictionary.put("umbrella", new DictionaryEntry("(n):", "dù", "He used an umbrella in the rain."));
        dictionary.put("shoe", new DictionaryEntry("(n):", "giày", "She bought a new pair of shoes."));
        dictionary.put("sock", new DictionaryEntry("(n):", "tất", "He wore warm socks in the winter."));
        dictionary.put("scarf", new DictionaryEntry("(n):", "khăn quàng cổ", "She wore a scarf around her neck."));
        dictionary.put("hat", new DictionaryEntry("(n):", "mũ", "He wore a hat to protect from the sun."));
        dictionary.put("jacket", new DictionaryEntry("(n):", "áo khoác", "She wore a jacket to stay warm."));
        dictionary.put("sandwich", new DictionaryEntry("(n):", "bánh sandwich", "He made a sandwich for lunch."));
        dictionary.put("cookie", new DictionaryEntry("(n):", "bánh quy", "She baked chocolate chip cookies."));
        dictionary.put("juice", new DictionaryEntry("(n):", "nước ép", "He drank a glass of orange juice."));
        dictionary.put("cake", new DictionaryEntry("(n):", "bánh kem", "They celebrated with a chocolate cake."));
        dictionary.put("flower", new DictionaryEntry("(n):", "hoa", "She received a bouquet of flowers."));
        dictionary.put("sky", new DictionaryEntry("(n):", "bầu trời", "The sky was filled with stars."));
        dictionary.put("sea", new DictionaryEntry("(n):", "biển", "They swam in the sea."));
        dictionary.put("river", new DictionaryEntry("(n):", "con sông", "The river was calm and clear."));
        dictionary.put("path", new DictionaryEntry("(n):", "con đường", "They walked along the path in the park."));
        dictionary.put("forest", new DictionaryEntry("(n):", "rừng", "The forest was dense and green."));
        dictionary.put("desert", new DictionaryEntry("(n):", "sa mạc", "The desert was hot and dry."));
        dictionary.put("beach", new DictionaryEntry("(n):", "bãi biển", "They relaxed on the sandy beach."));
        dictionary.put("hill", new DictionaryEntry("(n):", "đồi", "They climbed to the top of the hill."));
        dictionary.put("park", new DictionaryEntry("(n):", "công viên", "They spent the afternoon at the park."));
        dictionary.put("garden", new DictionaryEntry("(n):", "vườn", "She planted flowers in the garden."));
        dictionary.put("bridge", new DictionaryEntry("(n):", "cầu", "They crossed the bridge over the river."));
        dictionary.put("gate", new DictionaryEntry("(n):", "cổng", "The gate was locked."));
        dictionary.put("stair", new DictionaryEntry("(n):", "cầu thang", "She climbed the stairs quickly."));
        dictionary.put("floor", new DictionaryEntry("(n):", "sàn", "The floor was clean and polished."));
        dictionary.put("wall", new DictionaryEntry("(n):", "tường", "The wall was painted blue."));
        dictionary.put("ceiling", new DictionaryEntry("(n):", "trần", "The ceiling was high and white."));
        dictionary.put("roof", new DictionaryEntry("(n):", "mái nhà", "The roof was made of tiles."));
        dictionary.put("door", new DictionaryEntry("(n):", "cửa", "She opened the door slowly."));
        dictionary.put("window", new DictionaryEntry("(n):", "cửa sổ", "The window was covered with curtains."));
        dictionary.put("furniture", new DictionaryEntry("(n):", "đồ nội thất", "The furniture in the room was modern."));
        dictionary.put("apartment", new DictionaryEntry("(n):", "căn hộ", "They moved into a new apartment."));
        dictionary.put("house", new DictionaryEntry("(n):", "nhà", "Their house has a big garden."));
        dictionary.put("vase", new DictionaryEntry("(n):", "bình hoa", "She put flowers in the vase."));
        dictionary.put("mirror", new DictionaryEntry("(n):", "gương", "The mirror was hung on the wall."));
        dictionary.put("clock", new DictionaryEntry("(n):", "đồng hồ", "The clock on the wall was ticking."));
        dictionary.put("lamp", new DictionaryEntry("(n):", "đèn bàn", "She turned on the lamp to read."));
        dictionary.put("computer", new DictionaryEntry("(n):", "máy tính", "His computer is very powerful."));
        dictionary.put("keyboard", new DictionaryEntry("(n):", "bàn phím", "He typed on the keyboard."));
        dictionary.put("mouse", new DictionaryEntry("(n):", "chuột máy tính", "She clicked the mouse."));
        dictionary.put("printer", new DictionaryEntry("(n):", "máy in", "The printer ran out of ink."));
        dictionary.put("internet", new DictionaryEntry("(n):", "mạng internet", "He connected to the internet."));
        dictionary.put("website", new DictionaryEntry("(n):", "trang web", "She visited a new website."));
        dictionary.put("email", new DictionaryEntry("(n):", "email", "He sent an email to his friend."));
        dictionary.put("message", new DictionaryEntry("(n):", "tin nhắn", "She received a message on her phone."));
        dictionary.put("chat", new DictionaryEntry("(n):", "trò chuyện", "They had a chat over coffee."));
        dictionary.put("call", new DictionaryEntry("(n):", "cuộc gọi", "He made a call to his colleague."));
        dictionary.put("giraffe", new DictionaryEntry("(n):", "hươu cao cổ", "The giraffe is the tallest land animal."));
        dictionary.put("eagle", new DictionaryEntry("(n):", "đại bàng", "The eagle soared high in the sky."));
        dictionary.put("pen", new DictionaryEntry("(n):", "bút", "He wrote a letter with a pen."));
        dictionary.put("bottle", new DictionaryEntry("(n):", "chai", "She filled the bottle with water."));
        dictionary.put("city", new DictionaryEntry("(n):", "thành phố", "They live in a bustling city."));
        dictionary.put("ball", new DictionaryEntry("(n):", "quả bóng", "The children played with a ball."));
        dictionary.put("table", new DictionaryEntry("(n):", "bàn", "The table was set for dinner."));
        dictionary.put("bed", new DictionaryEntry("(n):", "giường", "He slept on a comfortable bed."));
        dictionary.put("camera", new DictionaryEntry("(n):", "máy ảnh", "She used the camera to take photos."));
        dictionary.put("shirt", new DictionaryEntry("(n):", "áo sơ mi", "He wore a blue shirt to the meeting."));
        dictionary.put("phone", new DictionaryEntry("(n):", "điện thoại", "He answered the phone immediately."));
        dictionary.put("laptop", new DictionaryEntry("(n):", "máy tính xách tay", "She worked on her laptop all day."));
        dictionary.put("book", new DictionaryEntry("(n):", "sách", "He borrowed a book from the library."));
        dictionary.put("notebook", new DictionaryEntry("(n):", "sổ tay", "She took notes in her notebook."));
        dictionary.put("dictionary", new DictionaryEntry("(n):", "từ điển", "He looked up the word in the dictionary."));
        dictionary.put("bowl", new DictionaryEntry("(n):", "bát", "She served soup in a large bowl."));
        dictionary.put("fork", new DictionaryEntry("(n):", "dĩa", "He used a fork to eat his dinner."));
        dictionary.put("plate", new DictionaryEntry("(n):", "đĩa", "The food was served on a plate."));
        dictionary.put("glass", new DictionaryEntry("(n):", "ly", "She poured juice into a glass."));

        dictionary.put("street", new DictionaryEntry("(n):", "phố", "  \nShe lived on a quiet street."));
        dictionary.put("avenue", new DictionaryEntry("(n):", "đại lộ", "  \nThe avenue was lined with trees."));
        dictionary.put("city", new DictionaryEntry("(n):", "thành phố", "  \nNew York is a large city."));
        dictionary.put("town", new DictionaryEntry("(n):", "thị trấn", "  \nThey lived in a small town."));
        dictionary.put("village", new DictionaryEntry("(n):", "làng", "  \nThe village was surrounded by fields."));
        dictionary.put("country", new DictionaryEntry("(n):", "quốc gia", "  \nHe traveled to a different country."));
        dictionary.put("continent", new DictionaryEntry("(n):", "châu lục", "  \nAfrica is a diverse continent."));
        dictionary.put("ocean", new DictionaryEntry("(n):", "đại dương", "  \nThe ocean was vast and deep."));
        dictionary.put("sea", new DictionaryEntry("(n):", "biển", "  \nThey went swimming in the sea."));
        dictionary.put("lake", new DictionaryEntry("(n):", "hồ", "  \nThe lake was calm and peaceful."));
        dictionary.put("river", new DictionaryEntry("(n):", "con sông", "  \nThe river flowed gently through the valley."));
        dictionary.put("stream", new DictionaryEntry("(n):", "suối", "  \nThe stream babbled over the rocks."));
        dictionary.put("waterfall", new DictionaryEntry("(n):", "thác nước", "  \nThe waterfall was breathtaking."));
        dictionary.put("mountain", new DictionaryEntry("(n):", "núi", "  \nThey hiked up the mountain."));
        dictionary.put("hill", new DictionaryEntry("(n):", "đồi", "  \nThe hill offered a great view."));
        dictionary.put("valley", new DictionaryEntry("(n):", "thung lũng", "  \nThe valley was covered in mist."));
        dictionary.put("desert", new DictionaryEntry("(n):", "sa mạc", "  \nThe desert was hot and dry."));
        dictionary.put("forest", new DictionaryEntry("(n):", "rừng", "  \nThe forest was dense and green."));
        dictionary.put("jungle", new DictionaryEntry("(n):", "rừng nhiệt đới", "  \nThe jungle was full of wildlife."));
        dictionary.put("cave", new DictionaryEntry("(n):", "hang động", "  \nThey explored the dark cave."));
        dictionary.put("cliff", new DictionaryEntry("(n):", "vách đá", "  \nThe cliff overlooked the ocean."));
        dictionary.put("beach", new DictionaryEntry("(n):", "bãi biển", "  \nThey relaxed on the sandy beach."));
        dictionary.put("sand", new DictionaryEntry("(n):", "cát", "  \nThe sand was warm beneath their feet."));
        dictionary.put("shell", new DictionaryEntry("(n):", "vỏ sò", "  \nShe collected seashells on the beach."));
        dictionary.put("star", new DictionaryEntry("(n):", "ngôi sao", "  \nThe stars were bright in the night sky."));
        dictionary.put("moon", new DictionaryEntry("(n):", "mặt trăng", "  \nThe moon shone brightly over the ocean."));
        dictionary.put("sun", new DictionaryEntry("(n):", "mặt trời", "  \nThe sun rose early in the morning."));
        dictionary.put("cloud", new DictionaryEntry("(n):", "đám mây", "  \nThe clouds were fluffy and white."));
        dictionary.put("rain", new DictionaryEntry("(n):", "mưa", "  \nThe rain fell softly on the ground."));
        dictionary.put("snow", new DictionaryEntry("(n):", "tuyết", "  \nThe snow covered the ground in a blanket."));
        dictionary.put("storm", new DictionaryEntry("(n):", "bão", "  \nThe storm caused a lot of damage."));
        dictionary.put("wind", new DictionaryEntry("(n):", "gió", "  \nThe wind rustled the leaves."));
        dictionary.put("temperature", new DictionaryEntry("(n):", "nhiệt độ", "  \nThe temperature dropped overnight."));
        dictionary.put("climate", new DictionaryEntry("(n):", "khí hậu", "  \nThe climate in the region is mild."));
        dictionary.put("weather", new DictionaryEntry("(n):", "thời tiết", "  \nThe weather was sunny and warm."));
        dictionary.put("forecast", new DictionaryEntry("(n):", "dự báo thời tiết", "  \nThe forecast predicted rain."));
        dictionary.put("season", new DictionaryEntry("(n):", "mùa", "  \nSpring is her favorite season."));
        dictionary.put("spring", new DictionaryEntry("(n):", "mùa xuân", "  \nThe flowers bloom in the spring."));
        dictionary.put("summer", new DictionaryEntry("(n):", "mùa hè", "  \nThey went on vacation in the summer."));
        dictionary.put("autumn", new DictionaryEntry("(n):", "mùa thu", "  \nThe leaves turn color in autumn."));
        dictionary.put("winter", new DictionaryEntry("(n):", "mùa đông", "  \nWinter is cold and snowy."));
        dictionary.put("holiday", new DictionaryEntry("(n):", "ngày lễ", "  \nThey celebrated the holiday with family."));
        dictionary.put("festival", new DictionaryEntry("(n):", "lễ hội", "  \nThe festival featured music and food."));
        dictionary.put("event", new DictionaryEntry("(n):", "sự kiện", "  \nThe event was a huge success."));
        dictionary.put("party", new DictionaryEntry("(n):", "bữa tiệc", "  \nThey threw a party for her birthday."));
        dictionary.put("celebration", new DictionaryEntry("(n):", "lễ kỷ niệm", "  \nThe celebration lasted all night."));
        dictionary.put("ceremony", new DictionaryEntry("(n):", "buổi lễ", "  \nThe ceremony was held in the afternoon."));
        dictionary.put("tradition", new DictionaryEntry("(n):", "truyền thống", "  \nThey followed the tradition closely."));
        dictionary.put("custom", new DictionaryEntry("(n):", "phong tục", "  \nIt is a custom to exchange gifts."));
        dictionary.put("culture", new DictionaryEntry("(n):", "văn hóa", "  \nThe culture of the region is rich and diverse."));
        dictionary.put("heritage", new DictionaryEntry("(n):", "di sản", "  \nThe heritage of the city is preserved in the museum."));
        dictionary.put("history", new DictionaryEntry("(n):", "lịch sử", "  \nShe studied the history of the country."));
        dictionary.put("past", new DictionaryEntry("(n):", "quá khứ", "  \nThe past is an important part of our lives."));
        dictionary.put("present", new DictionaryEntry("(n):", "hiện tại", "  \nThe present is where we live now."));
        dictionary.put("future", new DictionaryEntry("(n):", "tương lai", "  \nThey planned for the future."));
        dictionary.put("dream", new DictionaryEntry("(n):", "giấc mơ", "  \nShe had a dream about flying."));
        dictionary.put("hope", new DictionaryEntry("(n):", "hi vọng", "  \nHe had hope for a better future."));
        dictionary.put("wish", new DictionaryEntry("(n):", "ước", "  \nShe made a wish on a star."));
        dictionary.put("goal", new DictionaryEntry("(n):", "mục tiêu", "  \nHis goal is to become a doctor."));
        dictionary.put("achievement", new DictionaryEntry("(n):", "thành tựu", "  \nHer achievement was recognized by the community."));
        dictionary.put("success", new DictionaryEntry("(n):", "thành công", "  \nSuccess comes with hard work."));
        dictionary.put("failure", new DictionaryEntry("(n):", "thất bại", "  \nFailure is just a stepping stone to success."));
        dictionary.put("challenge", new DictionaryEntry("(n):", "thách thức", "  \nThe challenge was difficult but rewarding."));
        dictionary.put("problem", new DictionaryEntry("(n):", "vấn đề", "  \nThey solved the problem together."));
        dictionary.put("solution", new DictionaryEntry("(n):", "giải pháp", "  \nThe solution was effective and practical."));
        dictionary.put("question", new DictionaryEntry("(n):", "câu hỏi", "  \nShe asked a question during the lecture."));
        dictionary.put("answer", new DictionaryEntry("(n):", "câu trả lời", "  \nHe gave a clear answer to the question."));
        dictionary.put("advice", new DictionaryEntry("(n):", "lời khuyên", "  \nShe gave me valuable advice."));
        dictionary.put("suggestion", new DictionaryEntry("(n):", "gợi ý", "  \nHe made a suggestion for the project."));
        dictionary.put("opinion", new DictionaryEntry("(n):", "quan điểm", "  \nShe expressed her opinion on the matter."));
        dictionary.put("view", new DictionaryEntry("(n):", "quan điểm", "  \nHe had a different view on the topic."));
        dictionary.put("thought", new DictionaryEntry("(n):", "suy nghĩ", "  \nHis thoughts were focused on the future."));
        dictionary.put("idea", new DictionaryEntry("(n):", "ý tưởng", "  \nShe came up with a brilliant idea."));
        dictionary.put("concept", new DictionaryEntry("(n):", "khái niệm", "  \nThe concept was new and innovative."));
        dictionary.put("theory", new DictionaryEntry("(n):", "lý thuyết", "  \nHe studied the theory of relativity."));
        dictionary.put("principle", new DictionaryEntry("(n):", "nguyên tắc", "  \nThe principle was fundamental to the study."));
        dictionary.put("law", new DictionaryEntry("(n):", "luật", "  \nThe law was passed by the government."));
        dictionary.put("rule", new DictionaryEntry("(n):", "quy tắc", "  \nThe rule was clear and straightforward."));
        dictionary.put("regulation", new DictionaryEntry("(n):", "quy định", "  \nThe regulation ensured safety."));
        dictionary.put("policy", new DictionaryEntry("(n):", "chính sách", "  \nThe policy was implemented company-wide."));
        dictionary.put("procedure", new DictionaryEntry("(n):", "quy trình", "  \nThe procedure was followed step by step."));
        dictionary.put("method", new DictionaryEntry("(n):", "phương pháp", "  \nShe used a new method for the experiment."));
        dictionary.put("technique", new DictionaryEntry("(n):", "kỹ thuật", "  \nThe technique was advanced and precise."));
        dictionary.put("system", new DictionaryEntry("(n):", "hệ thống", "  \nThe system was designed to be efficient."));
        dictionary.put("process", new DictionaryEntry("(n):", "quá trình", "  \nThe process was complex but necessary."));
        dictionary.put("operation", new DictionaryEntry("(n):", "hoạt động", "  \nThe operation was successful and smooth."));
        dictionary.put("task", new DictionaryEntry("(n):", "nhiệm vụ", "  \nHe completed the task on time."));
        dictionary.put("activity", new DictionaryEntry("(n):", "hoạt động", "  \nThe activity was fun and engaging."));
        dictionary.put("project", new DictionaryEntry("(n):", "dự án", "  \nThe project was completed ahead of schedule."));
        dictionary.put("assignment", new DictionaryEntry("(n):", "bài tập", "  \nShe finished her assignment early."));
        dictionary.put("homework", new DictionaryEntry("(n):", "bài tập về nhà", "  \nHe did his homework after school."));
        dictionary.put("exam", new DictionaryEntry("(n):", "kỳ thi", "  \nThe exam was challenging but fair."));
        dictionary.put("test", new DictionaryEntry("(n):", "bài kiểm tra", "  \nShe studied hard for the test."));
        dictionary.put("apple", new DictionaryEntry("(n):", "táo", "  \nShe ate a juicy apple."));
        dictionary.put("banana", new DictionaryEntry("(n):", "chuối", "  \nBananas are rich in potassium."));
        dictionary.put("orange", new DictionaryEntry("(n):", "cam", "  \nHe drank a glass of orange juice."));
        dictionary.put("grape", new DictionaryEntry("(n):", "nho", "  \nShe bought a bunch of grapes."));
        dictionary.put("pineapple", new DictionaryEntry("(n):", "dứa", "  \nPineapple has a sweet and tangy flavor."));
        dictionary.put("watermelon", new DictionaryEntry("(n):", "dưa hấu", "  \nWatermelon is perfect for summer."));
        dictionary.put("strawberry", new DictionaryEntry("(n):", "dâu tây", "  \nShe topped her dessert with strawberries."));
        dictionary.put("blueberry", new DictionaryEntry("(n):", "việt quất", "  \nBlueberries are high in antioxidants."));
        dictionary.put("peach", new DictionaryEntry("(n):", "đào", "  \nHe enjoyed a peach pie."));
        dictionary.put("kiwi", new DictionaryEntry("(n):", "kiwi", "  \nKiwi fruit has a unique taste."));
        dictionary.put("mango", new DictionaryEntry("(n):", "xoài", "  \nMangoes are deliciously sweet."));
        dictionary.put("pear", new DictionaryEntry("(n):", "lê", "  \nShe had a ripe pear for breakfast."));
        dictionary.put("plum", new DictionaryEntry("(n):", "mận", "  \nPlums are used in many recipes."));
        dictionary.put("cherry", new DictionaryEntry("(n):", "quả anh đào", "  \nShe picked cherries from the tree."));
        dictionary.put("apricot", new DictionaryEntry("(n):", "quả mơ", "  \nApricots are great for jams."));
        dictionary.put("lemon", new DictionaryEntry("(n):", "chanh", "  \nLemonade is made from lemons."));
        dictionary.put("lime", new DictionaryEntry("(n):", "chanh xanh", "  \nLime adds zest to many dishes."));
        dictionary.put("coconut", new DictionaryEntry("(n):", "dừa", "  \nCoconut milk is used in many dishes."));
        dictionary.put("pomegranate", new DictionaryEntry("(n):", "lựu", "  \nPomegranate seeds are tart and juicy."));
        dictionary.put("date", new DictionaryEntry("(n):", "quả chà là", "  \nDates are sweet and chewy."));
        dictionary.put("fig", new DictionaryEntry("(n):", "quả sung", "  \nFigs are often eaten dried."));
        dictionary.put("apricot", new DictionaryEntry("(n):", "quả mơ", "  \nApricot jam is sweet and tangy."));
        dictionary.put("nut", new DictionaryEntry("(n):", "hạt", "  \nHe added nuts to his salad."));
        dictionary.put("almond", new DictionaryEntry("(n):", "hạt hạnh nhân", "  \nAlmonds are a healthy snack."));
        dictionary.put("walnut", new DictionaryEntry("(n):", "hạt óc chó", "  \nWalnuts are rich in omega-3 fatty acids."));
        dictionary.put("cashew", new DictionaryEntry("(n):", "hạt điều", "  \nCashews are used in many recipes."));
        dictionary.put("pecan", new DictionaryEntry("(n):", "hạt hồ đào", "  \nPecans are great in pies."));
        dictionary.put("hazelnut", new DictionaryEntry("(n):", "hạt phỉ", "  \nHazelnuts are often used in chocolates."));
        dictionary.put("pine nut", new DictionaryEntry("(n):", "hạt thông", "  \nPine nuts are used in pesto sauce."));
        dictionary.put("pumpkin", new DictionaryEntry("(n):", "bí đỏ", "  \nPumpkin pie is a popular dessert."));
        dictionary.put("zucchini", new DictionaryEntry("(n):", "bí ngòi", "  \nZucchini is a versatile vegetable."));
        dictionary.put("carrot", new DictionaryEntry("(n):", "cà rốt", "  \nCarrots are great for snacking."));
        dictionary.put("broccoli", new DictionaryEntry("(n):", "bông cải xanh", "  \nBroccoli is high in vitamins."));
        dictionary.put("spinach", new DictionaryEntry("(n):", "rau chân vịt", "  \nSpinach is rich in iron."));
        dictionary.put("lettuce", new DictionaryEntry("(n):", "rau diếp", "  \nLettuce is used in salads."));
        dictionary.put("cucumber", new DictionaryEntry("(n):", "dưa chuột", "  \nCucumber is refreshing in salads."));
        dictionary.put("tomato", new DictionaryEntry("(n):", "cà chua", "  \nTomatoes are used in many dishes."));
        dictionary.put("onion", new DictionaryEntry("(n):", "hành", "  \nOnions add flavor to many recipes."));
        dictionary.put("garlic", new DictionaryEntry("(n):", "tỏi", "  \nGarlic is used in cooking for its flavor."));
        dictionary.put("pepper", new DictionaryEntry("(n):", "ớt", "  \nPepper adds spice to food."));
        dictionary.put("salt", new DictionaryEntry("(n):", "muối", "  \nSalt is used to season dishes."));
        dictionary.put("sugar", new DictionaryEntry("(n):", "đường", "  \nSugar is used to sweeten desserts."));
        dictionary.put("honey", new DictionaryEntry("(n):", "mật ong", "  \nHoney is a natural sweetener."));
        dictionary.put("vinegar", new DictionaryEntry("(n):", "dấm", "  \nVinegar is used in dressings."));
        dictionary.put("oil", new DictionaryEntry("(n):", "dầu", "  \nOil is used for cooking."));
        dictionary.put("butter", new DictionaryEntry("(n):", "bơ", "  \nButter is used in baking and cooking."));
        dictionary.put("cream", new DictionaryEntry("(n):", "kem", "  \nCream is used in sauces and desserts."));
        dictionary.put("cheese", new DictionaryEntry("(n):", "phô mai", "  \nCheese is enjoyed in many dishes."));
        dictionary.put("yogurt", new DictionaryEntry("(n):", "sữa chua", "  \nYogurt can be a healthy snack."));
        dictionary.put("egg", new DictionaryEntry("(n):", "trứng", "  \nEggs are a versatile ingredient."));
        dictionary.put("bread", new DictionaryEntry("(n):", "bánh mỳ", "  \nBread is a staple food item."));
        dictionary.put("rice", new DictionaryEntry("(n):", "gạo", "  \nRice is a common side dish."));
        dictionary.put("pasta", new DictionaryEntry("(n):", "mì ống", "  \nPasta can be served with various sauces."));
        dictionary.put("noodle", new DictionaryEntry("(n):", "mì", "  \nNoodles are used in many Asian dishes."));
        dictionary.put("meat", new DictionaryEntry("(n):", "thịt", "  \nMeat is a source of protein."));
        dictionary.put("chicken", new DictionaryEntry("(n):", "gà", "  \nChicken is a popular meat choice."));
        dictionary.put("beef", new DictionaryEntry("(n):", "thịt bò", "  \nBeef is used in many hearty dishes."));
        dictionary.put("pork", new DictionaryEntry("(n):", "thịt heo", "  \nPork can be roasted or grilled."));
        dictionary.put("fish", new DictionaryEntry("(n):", "cá", "  \nFish is a healthy protein option."));
        dictionary.put("seafood", new DictionaryEntry("(n):", "hải sản", "  \nSeafood includes fish, shrimp, and crab."));
        dictionary.put("shrimp", new DictionaryEntry("(n):", "tôm", "  \nShrimp can be grilled or fried."));
        dictionary.put("crab", new DictionaryEntry("(n):", "cua", "  \nCrab is often enjoyed with butter."));
        dictionary.put("lobster", new DictionaryEntry("(n):", "tôm hùm", "  \nLobster is a delicacy in many cuisines."));
        dictionary.put("oyster", new DictionaryEntry("(n):", "sò", "  \nOysters can be eaten raw or cooked."));
        dictionary.put("clams", new DictionaryEntry("(n):", "ngao", "  \nClams are often used in chowder."));
        dictionary.put("mushroom", new DictionaryEntry("(n):", "nấm", "  \nMushrooms add umami to dishes."));
        dictionary.put("herb", new DictionaryEntry("(n):", "rau gia vị", "  \nHerbs like basil and parsley are used in cooking."));

        //Chủ đề rau
        dictionary.put("cabbage", new DictionaryEntry("(n):", "bắp cải", "  \nCabbage is used in many salads."));
        dictionary.put("cauliflower", new DictionaryEntry("(n):", "súp lơ", "  \nCauliflower can be roasted or steamed."));
        dictionary.put("beet", new DictionaryEntry("(n):", "củ cải đường", "  \nBeets are often used in salads."));
        dictionary.put("radish", new DictionaryEntry("(n):", "củ cải", "  \nRadishes add a crunchy texture to dishes."));
        dictionary.put("corn", new DictionaryEntry("(n):", "ngô", "  \nCorn is a popular side dish."));
        dictionary.put("pea", new DictionaryEntry("(n):", "đậu hà lan", "  \nPeas can be added to many recipes."));
        dictionary.put("bean", new DictionaryEntry("(n):", "đậu", "  \nBeans are a good source of protein."));
        dictionary.put("squash", new DictionaryEntry("(n):", "bí", "  \nSquash can be roasted or made into soup."));
        dictionary.put("sweet potato", new DictionaryEntry("(n):", "khoai lang", "  \nSweet potatoes can be baked or mashed."));
        dictionary.put("eggplant", new DictionaryEntry("(n):", "cà tím", "  \nEggplant is often used in Mediterranean dishes."));
        dictionary.put("zucchini", new DictionaryEntry("(n):", "bí ngòi", "  \nZucchini can be sautéed or grilled."));
        dictionary.put("spinach", new DictionaryEntry("(n):", "rau chân vịt", "  \nSpinach is rich in iron and vitamins."));
        dictionary.put("lettuce", new DictionaryEntry("(n):", "rau diếp", "  \nLettuce is commonly used in salads."));
        dictionary.put("arugula", new DictionaryEntry("(n):", "rau rocket", "  \nArugula adds a peppery flavor to salads."));
        dictionary.put("chard", new DictionaryEntry("(n):", "rau cải bẹ xanh", "  \nChard can be sautéed or added to soups."));
        dictionary.put("kale", new DictionaryEntry("(n):", "rau cải xoăn", "  \nKale is often used in smoothies and salads."));
        dictionary.put("celery", new DictionaryEntry("(n):", "cần tây", "  \nCelery is a crunchy addition to salads."));
        dictionary.put("leek", new DictionaryEntry("(n):", "hẹ", "  \nLeeks are often used in soups and stews."));
        dictionary.put("onion", new DictionaryEntry("(n):", "hành", "  \nOnions add flavor to many dishes."));
        dictionary.put("garlic", new DictionaryEntry("(n):", "tỏi", "  \nGarlic is used to enhance the taste of food."));
        dictionary.put("ginger", new DictionaryEntry("(n):", "gừng", "  \nGinger adds a spicy kick to dishes."));
        dictionary.put("turmeric", new DictionaryEntry("(n):", "nghệ", "  \nTurmeric is used for its color and flavor."));
        dictionary.put("bell pepper", new DictionaryEntry("(n):", "ớt chuông", "  \nBell peppers come in various colors."));
        dictionary.put("jalapeno", new DictionaryEntry("(n):", "ớt jalapeno", "  \nJalapenos add heat to recipes."));
        dictionary.put("chili", new DictionaryEntry("(n):", "ớt", "  \nChili peppers are used in many spicy dishes."));
        dictionary.put("mushroom", new DictionaryEntry("(n):", "nấm", "  \nMushrooms are versatile and can be used in many dishes."));
        dictionary.put("asparagus", new DictionaryEntry("(n):", "măng tây", "  \nAsparagus can be grilled or steamed."));
        dictionary.put("artichoke", new DictionaryEntry("(n):", "atiso", "  \nArtichokes are often served as appetizers."));
        dictionary.put("beetroot", new DictionaryEntry("(n):", "củ cải đỏ", "  \nBeetroot can be used in salads and juices."));
        dictionary.put("chili pepper", new DictionaryEntry("(n):", "ớt", "  \nChili peppers are used to add spice."));
        dictionary.put("cilantro", new DictionaryEntry("(n):", "ngò rí", "  \nCilantro is used to garnish dishes."));
        dictionary.put("dill", new DictionaryEntry("(n):", "thì là", "  \nDill is used to flavor pickles and sauces."));
        dictionary.put("fennel", new DictionaryEntry("(n):", "thì là", "  \nFennel has a licorice-like flavor."));
        dictionary.put("thyme", new DictionaryEntry("(n):", "cỏ xạ hương", "  \nThyme is used in many savory dishes."));
        dictionary.put("rosemary", new DictionaryEntry("(n):", "hương thảo", "  \nRosemary adds a fragrant touch to meats."));
        dictionary.put("sage", new DictionaryEntry("(n):", "xô thơm", "  \nSage is often used in stuffing and sausages."));
        dictionary.put("bay leaf", new DictionaryEntry("(n):", "lá nguyệt quế", "  \nBay leaves are used to add flavor to stews."));
        dictionary.put("parsley", new DictionaryEntry("(n):", "mùi tây", "  \nParsley is used both as a garnish and an ingredient."));
        dictionary.put("chive", new DictionaryEntry("(n):", "hẹ", "  \nChives add a mild onion flavor to dishes."));
        dictionary.put("tarragon", new DictionaryEntry("(n):", "thì là", "  \nTarragon has a subtle anise flavor."));
        dictionary.put("mustard", new DictionaryEntry("(n):", "mù tạt", "  \nMustard seeds are used to make mustard sauce."));
        dictionary.put("coriander", new DictionaryEntry("(n):", "ngò", "  \nCoriander is used in many international dishes."));
        dictionary.put("pumpkin", new DictionaryEntry("(n):", "bí ngô", "  \nPumpkin can be used in soups and pies."));
        dictionary.put("squash", new DictionaryEntry("(n):", "bí", "  \nSquash can be roasted or made into soup."));
        dictionary.put("chili", new DictionaryEntry("(n):", "ớt", "  \nChili peppers add heat to dishes."));
        dictionary.put("okra", new DictionaryEntry("(n):", "quả đậu bắp", "  \nOkra is often used in Southern cooking."));
        dictionary.put("rhubarb", new DictionaryEntry("(n):", "rau cần tây", "  \nRhubarb is used in pies and crumbles."));
        dictionary.put("seaweed", new DictionaryEntry("(n):", "rong biển", "  \nSeaweed is often used in Asian cuisine."));
        dictionary.put("bean sprout", new DictionaryEntry("(n):", "giá đỗ", "  \nBean sprouts add crunch to stir-fries."));
        dictionary.put("fennel", new DictionaryEntry("(n):", "thì là", "  \nFennel is used in salads and as a seasoning."));
        dictionary.put("radicchio", new DictionaryEntry("(n):", "cải radicchio", "  \nRadicchio adds a bitter flavor to salads."));
        dictionary.put("endive", new DictionaryEntry("(n):", "rau diếp", "  \nEndive is used in salads for its crisp texture."));
        dictionary.put("cress", new DictionaryEntry("(n):", "rau mầm", "  \nCress adds a peppery taste to salads."));
        dictionary.put("mustard greens", new DictionaryEntry("(n):", "rau cải mù tạt", "  \nMustard greens are often used in Southern cooking."));
        dictionary.put("collard greens", new DictionaryEntry("(n):", "rau cải xanh", "  \nCollard greens are a staple in Southern cuisine."));
        dictionary.put("sweet corn", new DictionaryEntry("(n):", "ngô ngọt", "  \nSweet corn is often enjoyed on the cob."));
        dictionary.put("jicama", new DictionaryEntry("(n):", "củ sắn", "  \nJicama adds a crisp texture to salads."));
        dictionary.put("daikon", new DictionaryEntry("(n):", "củ cải trắng", "  \nDaikon is often used in Asian dishes."));
        dictionary.put("kohlrabi", new DictionaryEntry("(n):", "củ cải cánh", "  \nKohlrabi can be eaten raw or cooked."));
        dictionary.put("rhubarb", new DictionaryEntry("(n):", "cần tây", "  \nRhubarb is used in pies and crumbles."));
        dictionary.put("cabbage", new DictionaryEntry("(n):", "bắp cải", "  \nCabbage is often used in coleslaw."));
        dictionary.put("celery root", new DictionaryEntry("(n):", "củ cần tây", "  \nCelery root can be mashed or roasted."));
        dictionary.put("chard", new DictionaryEntry("(n):", "rau cải bẹ", "  \nChard can be used in soups or as a side dish."));
        dictionary.put("kale", new DictionaryEntry("(n):", "cải xoăn", "  \nKale is often used in salads and smoothies."));
        dictionary.put("beetroot", new DictionaryEntry("(n):", "củ cải đỏ", "  \nBeetroot is often used in salads and juices."));
        dictionary.put("napa cabbage", new DictionaryEntry("(n):", "bắp cải napa", "  \nNapa cabbage is commonly used in Asian cuisine."));
        dictionary.put("chili pepper", new DictionaryEntry("(n):", "ớt", "  \nChili peppers are used to add spice."));
        dictionary.put("coriander", new DictionaryEntry("(n):", "ngò", "  \nCoriander is used in many international dishes."));
        dictionary.put("fennel", new DictionaryEntry("(n):", "thì là", "  \nFennel has a licorice-like flavor."));
        dictionary.put("radish", new DictionaryEntry("(n):", "củ cải", "  \nRadishes add a crisp crunch to salads."));
        dictionary.put("sorrel", new DictionaryEntry("(n):", "rau sorrel", "  \nSorrel has a tangy flavor and is used in soups."));
        dictionary.put("mizuna", new DictionaryEntry("(n):", "rau mizuna", "  \nMizuna adds a peppery flavor to salads."));
        dictionary.put("salsify", new DictionaryEntry("(n):", "củ salsify", "  \nSalsify is often used in soups and stews."));
        dictionary.put("chicory", new DictionaryEntry("(n):", "cải chicory", "  \nChicory can be used in salads or as a coffee substitute."));
        dictionary.put("cress", new DictionaryEntry("(n):", "rau mầm", "  \nCress adds a peppery flavor to salads."));
//Thành phố
        dictionary.put("city", new DictionaryEntry("(n):", "thành phố", "  \nNew York is a bustling city."));
        dictionary.put("town", new DictionaryEntry("(n):", "thị trấn", "  \nThey live in a small town."));
        dictionary.put("village", new DictionaryEntry("(n):", "làng", "  \nThe village is known for its charm."));
        dictionary.put("capital", new DictionaryEntry("(n):", "thủ đô", "  \nHanoi is the capital of Vietnam."));
        dictionary.put("metropolis", new DictionaryEntry("(n):", "đô thị lớn", "  \nTokyo is a major metropolis."));
        dictionary.put("suburb", new DictionaryEntry("(n):", "ngoại ô", "  \nThey live in a suburb of Paris."));
        dictionary.put("district", new DictionaryEntry("(n):", "quận", "  \nThe financial district is busy during the day."));
        dictionary.put("neighborhood", new DictionaryEntry("(n):", "khu phố", "  \nTheir neighborhood is quiet and safe."));
        dictionary.put("municipality", new DictionaryEntry("(n):", "thành phố quản lý", "  \nThe municipality oversees local services."));
        dictionary.put("urban", new DictionaryEntry("(adj):", "thuộc đô thị", "  \nUrban areas are densely populated."));
        dictionary.put("rural", new DictionaryEntry("(adj):", "thuộc nông thôn", "  \nRural areas are often less populated."));
        dictionary.put("skyscraper", new DictionaryEntry("(n):", "tòa nhà chọc trời", "  \nSkyscrapers dominate the city skyline."));
        dictionary.put("downtown", new DictionaryEntry("(n):", "trung tâm thành phố", "  \nDowntown is the heart of the city."));
        dictionary.put("plaza", new DictionaryEntry("(n):", "quảng trường", "  \nThe plaza is a popular meeting spot."));
        dictionary.put("boulevard", new DictionaryEntry("(n):", "đại lộ", "  \nThe boulevard is lined with shops and cafes."));
        dictionary.put("avenue", new DictionaryEntry("(n):", "đường phố", "  \nThe avenue is famous for its historic buildings."));
        dictionary.put("street", new DictionaryEntry("(n):", "phố", "  \nThey live on Elm Street."));
        dictionary.put("square", new DictionaryEntry("(n):", "quảng trường", "  \nThe town square hosts weekly markets."));
        dictionary.put("bridge", new DictionaryEntry("(n):", "cầu", "  \nThe bridge connects the two sides of the city."));
        dictionary.put("tunnel", new DictionaryEntry("(n):", "hầm", "  \nThe tunnel runs under the river."));
        dictionary.put("subway", new DictionaryEntry("(n):", "tàu điện ngầm", "  \nThe subway is a quick way to get around the city."));
        dictionary.put("bus stop", new DictionaryEntry("(n):", "trạm xe buýt", "  \nThe bus stop is just around the corner."));
        dictionary.put("train station", new DictionaryEntry("(n):", "ga tàu", "  \nThe train station is always busy."));
        dictionary.put("airport", new DictionaryEntry("(n):", "sân bay", "  \nThe airport is located on the outskirts of the city."));
        dictionary.put("harbor", new DictionaryEntry("(n):", "cảng", "  \nThe harbor is used for cargo and passenger ships."));
        dictionary.put("dock", new DictionaryEntry("(n):", "bến tàu", "  \nThe dock is where the fishing boats are moored."));
        dictionary.put("plaza", new DictionaryEntry("(n):", "quảng trường", "  \nThe plaza is a popular gathering place."));
        dictionary.put("shopping mall", new DictionaryEntry("(n):", "trung tâm mua sắm", "  \nThe shopping mall has many stores and restaurants."));
        dictionary.put("cultural center", new DictionaryEntry("(n):", "trung tâm văn hóa", "  \nThe cultural center hosts various events."));
        dictionary.put("museum", new DictionaryEntry("(n):", "bảo tàng", "  \nThe museum exhibits historical artifacts."));
        dictionary.put("library", new DictionaryEntry("(n):", "thư viện", "  \nThe library offers a wide range of books."));
        dictionary.put("park", new DictionaryEntry("(n):", "công viên", "  \nThe park is a great place for a picnic."));
        dictionary.put("garden", new DictionaryEntry("(n):", "vườn", "  \nThe garden is beautifully landscaped."));
        dictionary.put("zoo", new DictionaryEntry("(n):", "sở thú", "  \nThe zoo has many exotic animals."));
        dictionary.put("aquarium", new DictionaryEntry("(n):", "thủy cung", "  \nThe aquarium features marine life exhibits."));
        dictionary.put("stadium", new DictionaryEntry("(n):", "sân vận động", "  \nThe stadium hosts major sporting events."));
        dictionary.put("theater", new DictionaryEntry("(n):", "nhà hát", "  \nThe theater is known for its plays and performances."));
        dictionary.put("opera house", new DictionaryEntry("(n):", "nhà hát opera", "  \nThe opera house hosts classical music performances."));
        dictionary.put("concert hall", new DictionaryEntry("(n):", "hội trường hòa nhạc", "  \nThe concert hall is famous for its acoustics."));
        dictionary.put("university", new DictionaryEntry("(n):", "trường đại học", "  \nThe university has a prestigious reputation."));
        dictionary.put("college", new DictionaryEntry("(n):", "trường cao đẳng", "  \nThe college offers a variety of programs."));
        dictionary.put("hospital", new DictionaryEntry("(n):", "bệnh viện", "  \nThe hospital provides medical care."));
        dictionary.put("clinic", new DictionaryEntry("(n):", "phòng khám", "  \nThe clinic offers outpatient services."));
        dictionary.put("pharmacy", new DictionaryEntry("(n):", "hiệu thuốc", "  \nThe pharmacy dispenses prescription medications."));
        dictionary.put("post office", new DictionaryEntry("(n):", "bưu điện", "  \nThe post office handles mail and packages."));
        dictionary.put("bank", new DictionaryEntry("(n):", "ngân hàng", "  \nThe bank provides financial services."));
        dictionary.put("grocery store", new DictionaryEntry("(n):", "cửa hàng tạp hóa", "  \nThe grocery store sells food and household items."));
        dictionary.put("market", new DictionaryEntry("(n):", "chợ", "  \nThe market has fresh produce and local goods."));
        dictionary.put("restaurant", new DictionaryEntry("(n):", "nhà hàng", "  \nThe restaurant serves a variety of cuisines."));
        dictionary.put("cafe", new DictionaryEntry("(n):", "quán cà phê", "  \nThe cafe is a popular spot for coffee."));
        dictionary.put("bar", new DictionaryEntry("(n):", "quán bar", "  \nThe bar offers a selection of drinks."));
        dictionary.put("pub", new DictionaryEntry("(n):", "quán rượu", "  \nThe pub has a cozy atmosphere."));
        dictionary.put("shirt", new DictionaryEntry("(n):", "áo sơ mi", "  \nHe wore a blue shirt to the meeting."));
        dictionary.put("blouse", new DictionaryEntry("(n):", "áo sơ mi nữ", "  \nShe wore a floral blouse for the occasion."));
        dictionary.put("jacket", new DictionaryEntry("(n):", "áo khoác", "  \nHe wore a leather jacket in the winter."));
        dictionary.put("coat", new DictionaryEntry("(n):", "áo choàng", "  \nShe bought a new coat for the cold season."));
        dictionary.put("sweater", new DictionaryEntry("(n):", "áo len", "  \nHe wore a sweater to keep warm."));
        dictionary.put("vest", new DictionaryEntry("(n):", "áo ghi lê", "  \nHe wore a vest over his shirt."));
        dictionary.put("t-shirt", new DictionaryEntry("(n):", "áo phông", "  \nThe t-shirt had a funny slogan on it."));
        dictionary.put("hoodie", new DictionaryEntry("(n):", "áo hoodie", "  \nShe wore a hoodie for a casual look."));
        dictionary.put("suit", new DictionaryEntry("(n):", "com lê", "  \nHe wore a suit to the wedding."));
        dictionary.put("tie", new DictionaryEntry("(n):", "cà vạt", "  \nHe chose a red tie to match his suit."));
        dictionary.put("scarf", new DictionaryEntry("(n):", "khăn quàng cổ", "  \nShe wrapped a scarf around her neck for warmth."));
        dictionary.put("gloves", new DictionaryEntry("(n):", "găng tay", "  \nHe put on gloves before going outside."));
        dictionary.put("hat", new DictionaryEntry("(n):", "mũ", "  \nShe wore a hat to shield her face from the sun."));
        dictionary.put("cap", new DictionaryEntry("(n):", "mũ lưỡi trai", "  \nHe wore a baseball cap to keep the sun out of his eyes."));
        dictionary.put("beanie", new DictionaryEntry("(n):", "mũ len", "  \nShe wore a beanie to keep her head warm."));
        dictionary.put("shorts", new DictionaryEntry("(n):", "quần soóc", "\nHe wore shorts to the beach."));
        dictionary.put("jeans", new DictionaryEntry("(n):", "quần jeans", "  \nShe wore jeans and a t-shirt for a casual day out."));
        dictionary.put("trousers", new DictionaryEntry("(n):", "quần tây", "  \nHe wore formal trousers to the office."));
        dictionary.put("skirt", new DictionaryEntry("(n):", "váy", "  \nShe wore a skirt to the party."));
        dictionary.put("dress", new DictionaryEntry("(n):", "đầm", "  \nThe dress she wore was very elegant."));
        dictionary.put("suitcase", new DictionaryEntry("(n):", "vaxampleli", "  \nHe packed his clothes in a suitcase for the trip."));
        dictionary.put("bag", new DictionaryEntry("(n):", "túi", "  \nShe carried a bag with her essentials."));
        dictionary.put("belt", new DictionaryEntry("(n):", "thắt lưng", "  \nHe used a belt to keep his trousers up."));
        dictionary.put("shoes", new DictionaryEntry("(n):", "giày", "  \nShe bought a new pair of shoes for the party."));
        dictionary.put("boots", new DictionaryEntry("(n):", "giày ủng", "  \nHe wore boots for hiking."));
        dictionary.put("sandals", new DictionaryEntry("(n):", "dép", "  \nShe wore sandals to the beach."));
        dictionary.put("slippers", new DictionaryEntry("(n):", "dép đi trong nhà", "  \nHe wore slippers around the house."));
        dictionary.put("sneakers", new DictionaryEntry("(n):", "giày thể thao", "  \nShe wore sneakers for her morning run."));
        dictionary.put("underwear", new DictionaryEntry("(n):", "đồ lót", "  \nHe packed enough underwear for the trip."));
        dictionary.put("socks", new DictionaryEntry("(n):", "tất", "  \nShe wore warm socks in the winter."));
        dictionary.put("pyjamas", new DictionaryEntry("(n):", "pijama", "  \nHe wore pyjamas to bed."));
        dictionary.put("robe", new DictionaryEntry("(n):", "áo choàng tắm", "  \nShe wore a robe after her bath."));
        dictionary.put("pajamas", new DictionaryEntry("(n):", "đồ ngủ", "  \nHe wore pajamas to stay comfortable at home."));
        dictionary.put("overalls", new DictionaryEntry("(n):", "yếm", "  \nHe wore overalls while working in the garden."));
        dictionary.put("parka", new DictionaryEntry("(n):", "áo khoác dày", "  \nShe wore a parka to keep warm in the snow."));
        dictionary.put("head", new DictionaryEntry("(n):", "đầu", "  \nHe had a headache and needed to rest."));
        dictionary.put("eye", new DictionaryEntry("(n):", "mắt", "  \nShe wore glasses to protect her eyes."));
        dictionary.put("ear", new DictionaryEntry("(n):", "tai", "  \nHe had an ear infection and went to the doctor."));
        dictionary.put("nose", new DictionaryEntry("(n):", "mũi", "  \nShe had a cold and her nose was stuffy."));
        dictionary.put("mouth", new DictionaryEntry("(n):", "miệng", "  \nHe smiled and showed his teeth."));
        dictionary.put("tooth", new DictionaryEntry("(n):", "răng", "  \nShe brushed her teeth before bed."));
        dictionary.put("tongue", new DictionaryEntry("(n):", "lưỡi", "  \nHe burnt his tongue on the hot coffee."));
        dictionary.put("neck", new DictionaryEntry("(n):", "cổ", "  \nShe wore a necklace around her neck."));
        dictionary.put("shoulder", new DictionaryEntry("(n):", "vai", "  \nHe carried a heavy bag on his shoulder."));
        dictionary.put("arm", new DictionaryEntry("(n):", "cánh tay", "  \nShe broke her arm while playing sports."));
        dictionary.put("elbow", new DictionaryEntry("(n):", "khuỷu tay", "  \nHe rested his elbow on the table."));
        dictionary.put("hand", new DictionaryEntry("(n):", "bàn tay", "  \nShe waved her hand to say goodbye."));
        dictionary.put("finger", new DictionaryEntry("(n):", "ngón tay", "  \nHe cut his finger while cooking."));
        dictionary.put("chest", new DictionaryEntry("(n):", "ngực", "  \nHe felt a pain in his chest and went to the doctor."));
        dictionary.put("stomach", new DictionaryEntry("(n):", "dạ dày", "  \nShe felt a knot in her stomach from anxiety."));
        dictionary.put("back", new DictionaryEntry("(n):", "lưng", "  \nHe had a sore back after lifting heavy boxes."));
        dictionary.put("waist", new DictionaryEntry("(n):", "eo", "  \nShe tied a belt around her waist."));
        dictionary.put("hip", new DictionaryEntry("(n):", "hông", "  \nHe injured his hip while running."));
        dictionary.put("leg", new DictionaryEntry("(n):", "chân", "  \nShe broke her leg while skiing."));
        dictionary.put("knee", new DictionaryEntry("(n):", "đầu gối", "  \nHe bent his knee to tie his shoes."));
        dictionary.put("ankle", new DictionaryEntry("(n):", "cổ chân", "  \nShe sprained her ankle during the hike."));
        dictionary.put("foot", new DictionaryEntry("(n):", "bàn chân", "  \nHe stepped on a sharp object with his foot."));
        dictionary.put("toe", new DictionaryEntry("(n):", "ngón chân", "  \nShe stubbed her toe on the doorframe."));
        dictionary.put("skin", new DictionaryEntry("(n):", "da", "  \nShe applied sunscreen to protect her skin."));
        dictionary.put("hair", new DictionaryEntry("(n):", "tóc", "  \nHe cut his hair short for the summer."));
        dictionary.put("face", new DictionaryEntry("(n):", "khuôn mặt", "  \nShe had a smile on her face."));
        dictionary.put("cheek", new DictionaryEntry("(n):", "má", "  \nHe felt a warm blush on his cheek."));
        dictionary.put("chin", new DictionaryEntry("(n):", "cằm", "  \nShe rested her chin on her hand."));
        dictionary.put("forehead", new DictionaryEntry("(n):", "trán", "  \nHe wiped sweat from his forehead."));
        dictionary.put("eyebrow", new DictionaryEntry("(n):", "lông mày", "  \nShe raised an eyebrow in surprise."));
        dictionary.put("eyelash", new DictionaryEntry("(n):", "lông mi", "  \nShe used mascara to darken her eyelashes."));
        dictionary.put("palm", new DictionaryEntry("(n):", "lòng bàn tay", "  \nHe held the object in his palm."));
        dictionary.put("sunny", new DictionaryEntry("(adj):", "nắng", "  \nIt was a sunny day perfect for a picnic."));
        dictionary.put("cloudy", new DictionaryEntry("(adj):", "mây mù", "  \nThe sky was cloudy and overcast."));
        dictionary.put("rainy", new DictionaryEntry("(adj):", "mưa", "  \nIt was a rainy day and she carried an umbrella."));
        dictionary.put("stormy", new DictionaryEntry("(adj):", "bão tố", "  \nThe weather was stormy with strong winds."));
        dictionary.put("windy", new DictionaryEntry("(adj):", "gió", "  \nIt was too windy to go sailing."));
        dictionary.put("foggy", new DictionaryEntry("(adj):", "sương mù", "  \nThe morning was foggy and visibility was low."));
        dictionary.put("snowy", new DictionaryEntry("(adj):", "tuyết", "  \nThe ground was covered in a snowy blanket."));
        dictionary.put("hail", new DictionaryEntry("(n):", "mưa đá", "  \nThe storm included hailstones the size of marbles."));
        dictionary.put("drizzle", new DictionaryEntry("(n):", "mưa phùn", "  \nA light drizzle began in the late afternoon."));
        dictionary.put("shower", new DictionaryEntry("(n):", "mưa rào", "  \nThere were intermittent showers throughout the day."));
        dictionary.put("heatwave", new DictionaryEntry("(n):", "đợt nắng nóng", "  \nThe city was experiencing a heatwave."));
        dictionary.put("cold front", new DictionaryEntry("(n):", "đợt không khí lạnh", "  \nA cold front moved in, dropping temperatures quickly."));
        dictionary.put("humidity", new DictionaryEntry("(n):", "độ ẩm", "  \nThe humidity made the air feel thick and sticky."));
        dictionary.put("barometer", new DictionaryEntry("(n):", "áp kế", "  \nThe barometer showed a drop in air pressure."));
        dictionary.put("thermometer", new DictionaryEntry("(n):", "nhiệt kế", "  \nThe thermometer read 30 degrees Celsius."));
        dictionary.put("forecast", new DictionaryEntry("(n):", "dự báo thời tiết", "  \nThe weather forecast predicted rain for the weekend."));
        dictionary.put("temperature", new DictionaryEntry("(n):", "nhiệt độ", "  \nThe temperature dropped significantly after sunset."));
        dictionary.put("tornado", new DictionaryEntry("(n):", "lốc xoáy", "  \nA tornado caused extensive damage in the area."));
        dictionary.put("hurricane", new DictionaryEntry("(n):", "bão", "  \nThe hurricane made landfall and caused severe flooding."));
        dictionary.put("typhoon", new DictionaryEntry("(n):", "bão nhiệt đới", "  \nThe typhoon brought heavy rains and strong winds."));
        dictionary.put("cyclone", new DictionaryEntry("(n):", "vùng áp thấp", "  \nThe cyclone moved across the Indian Ocean."));
        dictionary.put("sunrise", new DictionaryEntry("(n):", "bình minh", "  \nShe watched the sunrise from the beach."));
        dictionary.put("sunset", new DictionaryEntry("(n):", "hoàng hôn", "  \nThe sunset painted the sky with beautiful colors."));
        dictionary.put("drought", new DictionaryEntry("(n):", "hạn hán", "  \nThe region faced a severe drought this year."));
        dictionary.put("rainbow", new DictionaryEntry("(n):", "cầu vồng", "  \nA rainbow appeared after the rainstorm."));
        dictionary.put("frost", new DictionaryEntry("(n):", "sương giá", "  \nFrost covered the ground early in the morning."));
        dictionary.put("ice", new DictionaryEntry("(n):", "băng", "  \nThe lake was covered in a thick layer of ice."));
        dictionary.put("dew", new DictionaryEntry("(n):", "sương", "  \nThe grass was covered in dew in the early morning."));
        dictionary.put("overcast", new DictionaryEntry("(adj):", "mây mù", "  \nThe sky was overcast and gray throughout the day."));
        dictionary.put("clear", new DictionaryEntry("(adj):", "quang đãng", "  \nThe sky was clear and blue, with no clouds in sight."));
        dictionary.put("mild", new DictionaryEntry("(adj):", "ôn hòa", "  \nThe weather was mild and comfortable, not too hot or cold."));
        dictionary.put("pleasant", new DictionaryEntry("(adj):", "dễ chịu", "  \nThe day was pleasantly warm with a gentle breeze."));
         dictionary.put("chilly", new DictionaryEntry("(adj):", "lạnh lẽo", ":\nThe evening turned chilly, and she needed a jacket."));


        addMessageToChat("Hãy gửi từ bạn cần giải nghĩa, Dolphin sẽ giúp bạn", false);
        sendButton.setOnClickListener(v -> handleSendButtonClick());


    }

    private void handleSendButtonClick() {
        String inputText = messageInput.getText().toString().trim();



        if (!inputText.isEmpty()) {
            DictionaryEntry entry = dictionary.get(inputText);
            String response = (entry != null) ? entry.toString() : "Mình chưa nhận diện được từ này. Bạn hãy kiểm tra lại hoặc thử từ khác.";


            addMessageToChat("Bạn: " + inputText, true);


            addMessageToChat("Dolphin: " + response, false);


            
            messageInput.setText("");
        }
    }

    private void addMessageToChat(String message, boolean isUser) {
        TextView textView = new TextView(this);
        textView.setText(message);
        textView.setPadding(10, 10, 10, 10);

        // Đổi màu nền dựa trên là tin nhắn của người dùng hay của bot
        int backgroundColor = isUser ? getResources().getColor(R.color.user_message_color) : getResources().getColor(R.color.bot_message_color);
        textView.setBackgroundColor(backgroundColor);

        chatContainer.addView(textView);

        // Scroll to the bottom of the ScrollView
        scrollView.post(() -> scrollView.fullScroll(View.FOCUS_DOWN));
    }



}